name: Build and Run

on:
  workflow_dispatch:
    inputs:
      input-json:
        description: 'JSON file path'
        required: true
        type: string
      liquid-string:
        description: 'Liquid file path'
        required: true
        type: string

  workflow_call:
    inputs:
      input-json:
        description: 'JSON file path'
        required: true
        type: string
      liquid-string:
        description: 'Liquid file path'
        required: true
        type: string
    outputs:
      output-json:
        description: 'The output JSON file'
        value: ${{ jobs.build-and-run.outputs.output-json }}

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    outputs:
      #output-json: ${{ steps.upload-output.outputs.output-json }}
      output-json: ./output.json
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Save input JSON to file
      run: |
            echo ${{ github.event.inputs.input-json }}
    #       echo ${{ github.event.inputs.input-json }} | base64 --decode >> input.json

    - name: Save Liquid string to file
      run: |
           echo ${{ github.event.inputs.liquid-string }}
    #      echo ${{ github.event.inputs.liquid-string }} >> transform.liquid

    - name: Run the project
      run: dotnet run --configuration Release ${{ github.event.inputs.input-json }} ${{ github.event.inputs.liquid-string }} ./output.json >> logs.txt

    - name: Upload Logs as artifact
      id: upload-output
      run: |
          echo "## CloudLiquid Logs 🚀" >> $GITHUB_STEP_SUMMARY
          echo "```json" >> $GITHUB_STEP_SUMMARY
          echo ./output.json >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          echo ./logs.txt >> $GITHUB_STEP_SUMMARY
