name: Call Build and Run

on:
  workflow_dispatch:

jobs:
  read-files:
    runs-on: ubuntu-latest
    steps:
    - name: Read liquid file
      id: read_liquid
      run: echo "liquid-string=$(cat liquid/salesforceCloudLiquid.liquid)" >> $GITHUB_ENV
    - name: Read JSON file
      id: read_json
      run: echo "input-json=$(cat tests/data/salesforce.json)" >> $GITHUB_ENV

  call-build-and-run:
    needs: read-files
    uses: ./.github/workflows/run.yml
    with:
      input-json: ${{ env.input-json }}
      liquid-string: ${{ env.liquid-string }}

  upload-output:
    needs: call-build-and-run
    runs-on: ubuntu-latest
    steps:
    - name: Upload output.json as artifact
      uses: actions/upload-artifact@v3
      with:
        name: output-json
        path: ${{ needs.call-build-and-run.outputs.output-json }}
