name: Test LiquidConsole

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  read-files:
    runs-on: ubuntu-latest
    outputs:
      input_json: ${{ steps.read_json.outputs.json }}
      liquid_string: ${{ steps.read_liquid.outputs.liquid }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Read liquid file
      id: read_liquid
      run: |
        liquid=$(cat ./liquid/salesforceCloudLiquid.liquid)
        echo liquid=$liquid >> $GITHUB_OUTPUT
        echo $liquid
    - name: Read JSON file
      id: read_json
      run: |
        json=$(jq "." ./tests/data/salesforce.json)
        echo json=$json >> $GITHUB_OUTPUT
        echo $json

  call-build-and-run:
    needs: read-files
    uses: jcardoso13/LiquidConsole/.github/workflows/run.yml@main
    with:
      input-json: "tests/data/salesforce.json"
      liquid-string: "liquid/salesforceCloudLiquid.liquid"

  download-and-check-output:
    needs: call-build-and-run
    runs-on: ubuntu-latest
    steps:
    - name: Download output.json artifact
      uses: actions/download-artifact@v4
      with:
        name: output-json
        path: ./output

    - name: Display output.json
      run: cat ./output/output.json
