name: Test LiquidConsole

on:
  workflow_dispatch:
  push:
    branches:
      - none

jobs:
  read-files:
    runs-on: ubuntu-latest
    outputs:
      input_json: ${{ steps.read_json.outputs.json }}
      liquid_string: ${{ steps.read_liquid.outputs.liquid }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Read liquid file
      id: read_liquid
      run: |
        liquid=$(cat ./liquid/salesforceCloudLiquid.liquid)
        echo liquid=$liquid >> $GITHUB_OUTPUT
        echo $liquid
    - name: Read JSON file
      id: read_json
      run: |
        json=$(jq "." ./tests/data/salesforce.json)
        echo json=$json >> $GITHUB_OUTPUT
        echo $json

  call-build-and-run:
    needs: read-files
    uses: bdsoflow/gh-data-transform/.github/workflows/run.yml@main
    with:
      input-file: "tests/data/salesforce.json"
      liquid-string: "liquid/salesforceCloudLiquid.liquid"
      output-file: "output.json"

  download-and-check-output:
    needs: call-build-and-run
    runs-on: ubuntu-latest
    steps:
    - name: Download output.json artifact
      uses: actions/download-artifact@v4
      with:
        name: output.json
        path: ./output.json
  
#    - name: CSV export
#      uses: advanced-security/ghas-to-csv@v3
#      env:
#        GITHUB_PAT: ${{ secrets.TOKEN }}  # you need to set a PAT
#        SCOPE_NAME: jcardoso13/demo-csharp
#    - name: Upload CSV
#      uses: actions/upload-artifact@v4
#      with:
#        name: ghas-data
#        path: ${{ github.workspace }}/*.csv
#        if-no-files-found: error
