name: Test LiquidConsole

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  read-files:
    runs-on: ubuntu-latest
    outputs:
      input_json: ${{ steps.read_json.outputs.json }}
      liquid_string: ${{ steps.read_liquid.outputs.liquid }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Read liquid file
      id: read_liquid
      run: |
            liquid=$(cat ./liquid/salesforceCloudLiquid.liquid)
            echo liquid=$liquid >> $GITHUB_OUTPUT
            echo $liquid
    - name: Read JSON file
      id: read_json
      run: |
            json=$(jq "." ./tests/data/salesforce.json)
            echo json=$json >> $GITHUB_OUTPUT
            echo $json

  call-build-and-run:
    needs: read-files
    uses: jcardoso13/LiquidConsole/.github/workflows/run.yml@main
    with:
      input-json: ${{ needs.read-files.outputs.input_json }}
      liquid-string: ${{ needs.read-files.outputs.liquid_string }}

  upload-output:
    needs: call-build-and-run
    runs-on: ubuntu-latest
    steps:
    - name: Upload output.json as artifact
      uses: actions/upload-artifact@v3
      with:
        name: output-json
        path: ${{ needs.call-build-and-run.outputs.output-json }}
